var classes = [
    {
        "name": "ServerPlanning\\FirstFitPolicy",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "canHost",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "next",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "host",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "instances",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 7,
        "ccnMethodMax": 5,
        "externals": [
            "ServerPlanning\\FitnessPolicy",
            "ServerPlanning\\Server",
            "ServerPlanning\\VirtualMachine",
            "ServerPlanning\\VirtualMachine",
            "ServerPlanning\\InsufficientResourcesException",
            "ServerPlanning\\InsufficientResourcesException",
            "ServerPlanning\\InsufficientResourcesException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 67,
        "vocabulary": 13,
        "volume": 247.93,
        "difficulty": 36,
        "effort": 8925.46,
        "level": 0.03,
        "bugs": 0.08,
        "time": 496,
        "intelligentContent": 6.89,
        "number_operators": 22,
        "number_operands": 45,
        "number_operators_unique": 8,
        "number_operands_unique": 5,
        "cloc": 13,
        "loc": 59,
        "lloc": 46,
        "mi": 79.26,
        "mIwoC": 46.02,
        "commentWeight": 33.24,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.37,
        "relativeSystemComplexity": 36.37,
        "totalStructuralComplexity": 180,
        "totalDataComplexity": 1.86,
        "totalSystemComplexity": 181.86,
        "package": "ServerPlanning\\",
        "pageRank": 0.06,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "ServerPlanning\\ServerPanning",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "calculate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "ServerPlanning\\Server",
            "ServerPlanning\\FirstFitPolicy"
        ],
        "parents": [],
        "lcom": 1,
        "length": 17,
        "vocabulary": 9,
        "volume": 53.89,
        "difficulty": 4.8,
        "effort": 258.67,
        "level": 0.21,
        "bugs": 0.02,
        "time": 14,
        "intelligentContent": 11.23,
        "number_operators": 5,
        "number_operands": 12,
        "number_operators_unique": 4,
        "number_operands_unique": 5,
        "cloc": 5,
        "loc": 20,
        "lloc": 15,
        "mi": 96.79,
        "mIwoC": 61.82,
        "commentWeight": 34.97,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 5.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 5.33,
        "package": "ServerPlanning\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ServerPlanning\\Server",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCpu",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRam",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHdd",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateResource",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ServerPlanning\\InvalidResourceProvisionException"
        ],
        "parents": [],
        "lcom": 2,
        "length": 35,
        "vocabulary": 16,
        "volume": 140,
        "difficulty": 3,
        "effort": 420,
        "level": 0.33,
        "bugs": 0.05,
        "time": 23,
        "intelligentContent": 46.67,
        "number_operators": 9,
        "number_operands": 26,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 19,
        "loc": 52,
        "lloc": 33,
        "mi": 91.85,
        "mIwoC": 51.58,
        "commentWeight": 40.27,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 5,
        "totalDataComplexity": 12.5,
        "totalSystemComplexity": 17.5,
        "package": "ServerPlanning\\",
        "pageRank": 0.12,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "ServerPlanning\\VirtualMachine",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateResource",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCpu",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRam",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHdd",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ServerPlanning\\InvalidResourceProvisionException"
        ],
        "parents": [],
        "lcom": 2,
        "length": 35,
        "vocabulary": 16,
        "volume": 140,
        "difficulty": 3,
        "effort": 420,
        "level": 0.33,
        "bugs": 0.05,
        "time": 23,
        "intelligentContent": 46.67,
        "number_operators": 9,
        "number_operands": 26,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 17,
        "loc": 50,
        "lloc": 33,
        "mi": 90.85,
        "mIwoC": 51.58,
        "commentWeight": 39.27,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 5,
        "totalDataComplexity": 12.5,
        "totalSystemComplexity": 17.5,
        "package": "ServerPlanning\\",
        "pageRank": 0.18,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "ServerPlanning\\InsufficientResourcesException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "cpu",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "ram",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hdd",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "DomainException",
            "ServerPlanning\\Server",
            "ServerPlanning\\VirtualMachine",
            "ServerPlanning\\Server",
            "ServerPlanning\\VirtualMachine",
            "ServerPlanning\\Server",
            "ServerPlanning\\VirtualMachine"
        ],
        "parents": [
            "DomainException"
        ],
        "lcom": 3,
        "length": 24,
        "vocabulary": 8,
        "volume": 72,
        "difficulty": 1.5,
        "effort": 108,
        "level": 0.67,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 48,
        "number_operators": 3,
        "number_operands": 21,
        "number_operators_unique": 1,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 60.59,
        "mIwoC": 60.59,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 10.25,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 3.75,
        "totalSystemComplexity": 30.75,
        "package": "ServerPlanning\\",
        "pageRank": 0.08,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "ServerPlanning\\InvalidResourceProvisionException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "DomainException"
        ],
        "parents": [
            "DomainException"
        ],
        "lcom": 1,
        "length": 7,
        "vocabulary": 5,
        "volume": 16.25,
        "difficulty": 0,
        "effort": 0,
        "level": 1.43,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 7,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 71.69,
        "mIwoC": 71.69,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "ServerPlanning\\",
        "pageRank": 0.47,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    }
]